name=NIELIT ESP32 Practicals
version=1.0.3
author=Lovnish Verma
maintainer=Lovnish Verma
sentence=NIELIT ESP32 practical programs and examples.
paragraph=Educational ESP32 practical programs covering GPIO, sensors, IoT, MQTT, Firebase, camera and embedded machine learning.
category=Other
url=https://github.com/LovnishVerma/NIELIT-ESP32-Practicals
architectures=esp32
